name: Deploy Plugin to Hostinger

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Despliegue vía FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener el código
        uses: actions/checkout@v4
      - name: 📂 Sincronizar archivos al servidor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/wp-content/plugins/wp-mailscope/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            node_modules/**
            composer.json
            composer.lock
            README.md